/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qubic;

import java.awt.Component;

/**
 *
 * @author Nela
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
        ljestvica.setVisible(false);
        newGame.setVisible(false);
        stat.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        glavniPanel = new javax.swing.JPanel();
        prviIme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        posalji = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        drugiIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vrsta = new javax.swing.JComboBox<>();
        znakic = new javax.swing.JComboBox<>();
        naslovniPanel = new javax.swing.JPanel();
        uputa = new javax.swing.JLabel();
        naslov = new javax.swing.JLabel();
        napPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        newGame = new javax.swing.JButton();
        stat = new javax.swing.JButton();
        ljestvica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Igra QUBIC");
        setBackground(new java.awt.Color(239, 227, 191));

        glavniPanel.setBackground(new java.awt.Color(162, 213, 162));
        glavniPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Unesite svoje ime:");

        posalji.setBackground(new java.awt.Color(0, 153, 102));
        posalji.setForeground(new java.awt.Color(255, 255, 255));
        posalji.setText("Kreni!");
        posalji.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        posalji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posaljiMouseClicked(evt);
            }
        });
        posalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posaljiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Vrsta igre(ploče):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Drugi igrač:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Znakić prvog igrača:");

        vrsta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3x3", "4x4x4" }));

        znakic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "O" }));
        znakic.setToolTipText("");

        javax.swing.GroupLayout glavniPanelLayout = new javax.swing.GroupLayout(glavniPanel);
        glavniPanel.setLayout(glavniPanelLayout);
        glavniPanelLayout.setHorizontalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavniPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posalji, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, glavniPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prviIme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drugiIme, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vrsta, 0, 89, Short.MAX_VALUE)
                    .addComponent(znakic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        glavniPanelLayout.setVerticalGroup(
            glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(glavniPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prviIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(drugiIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(glavniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(znakic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(posalji)
                .addContainerGap())
        );

        uputa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        uputa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uputa.setText("Odaberite podatke za početak igre.");

        naslov.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        naslov.setForeground(new java.awt.Color(0, 153, 102));
        naslov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        naslov.setText("Dobrodošli u igru Qubic! ");

        javax.swing.GroupLayout naslovniPanelLayout = new javax.swing.GroupLayout(naslovniPanel);
        naslovniPanel.setLayout(naslovniPanelLayout);
        naslovniPanelLayout.setHorizontalGroup(
            naslovniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uputa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(naslov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        naslovniPanelLayout.setVerticalGroup(
            naslovniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naslovniPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naslov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(uputa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Napomena: za računalo kao drugog igrača u formu napišite računalo.");

        javax.swing.GroupLayout napPanelLayout = new javax.swing.GroupLayout(napPanel);
        napPanel.setLayout(napPanelLayout);
        napPanelLayout.setHorizontalGroup(
            napPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(napPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        napPanelLayout.setVerticalGroup(
            napPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, napPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        newGame.setBackground(new java.awt.Color(0, 153, 102));
        newGame.setForeground(new java.awt.Color(255, 255, 255));
        newGame.setText("Nova igra");
        jPanel1.add(newGame);

        stat.setBackground(new java.awt.Color(0, 153, 102));
        stat.setForeground(new java.awt.Color(255, 255, 255));
        stat.setText("Statistika");
        jPanel1.add(stat);

        ljestvica.setBackground(new java.awt.Color(0, 153, 102));
        ljestvica.setForeground(new java.awt.Color(255, 255, 255));
        ljestvica.setText("Ljestvica");
        jPanel1.add(ljestvica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(napPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(naslovniPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(glavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(naslovniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(glavniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(napPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posaljiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posaljiActionPerformed

    private void posaljiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posaljiMouseClicked
        //lista svih podkomponenti
        Component[] componentList = glavniPanel.getComponents();
        for(Component c : componentList){
            glavniPanel.remove(c);
        }
        glavniPanel.revalidate();
        glavniPanel.repaint();
        this.remove(glavniPanel);
        ljestvica.setVisible(true);
        newGame.setVisible(true);
        stat.setVisible(true);
        
        naslov.setText("Igra " + prviIme.getText() + " vs " + drugiIme.getText() + " je započela! Sretno!");
        
        String tip = vrsta.getSelectedItem().toString();
        uputa.setText(tip);
    }//GEN-LAST:event_posaljiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void pozovi() {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField drugiIme;
    private javax.swing.JPanel glavniPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ljestvica;
    private javax.swing.JPanel napPanel;
    private javax.swing.JLabel naslov;
    private javax.swing.JPanel naslovniPanel;
    private javax.swing.JButton newGame;
    private javax.swing.JButton posalji;
    private javax.swing.JTextField prviIme;
    private javax.swing.JButton stat;
    private javax.swing.JLabel uputa;
    private javax.swing.JComboBox<String> vrsta;
    private javax.swing.JComboBox<String> znakic;
    // End of variables declaration//GEN-END:variables
}
