/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qubic;
/**
 *
 * @author Nela
 */
public class ljestvicaPop extends javax.swing.JFrame {

    /**
     * Creates new form ljestvicaPop
     */
    public ljestvicaPop() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        topx3.setEditable(false);
        topx3.setText(Baza.getLjestvica("X", "3x3x3"));
        topo3.setEditable(false);
        topo3.setText(Baza.getLjestvica("O", "3x3x3"));
        topx4.setEditable(false);
        topx4.setText(Baza.getLjestvica("X", "4x4x4"));
        topo4.setEditable(false);
        topo4.setText(Baza.getLjestvica("O", "4x4x4"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        topx3 = new javax.swing.JTextArea();
        o3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        topo3 = new javax.swing.JTextArea();
        x4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        topx4 = new javax.swing.JTextArea();
        o4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        topo4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 2));

        x3.setBackground(new java.awt.Color(204, 255, 204));
        x3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Najbolji X igrači u 3x3x3 igri:");

        topx3.setEditable(false);
        topx3.setColumns(20);
        topx3.setRows(5);
        jScrollPane4.setViewportView(topx3);

        javax.swing.GroupLayout x3Layout = new javax.swing.GroupLayout(x3);
        x3.setLayout(x3Layout);
        x3Layout.setHorizontalGroup(
            x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        x3Layout.setVerticalGroup(
            x3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(x3);

        o3.setBackground(new java.awt.Color(204, 204, 204));
        o3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Najbolji O igrači u 3x3x3 igri:");

        topo3.setEditable(false);
        topo3.setColumns(20);
        topo3.setRows(5);
        jScrollPane1.setViewportView(topo3);

        javax.swing.GroupLayout o3Layout = new javax.swing.GroupLayout(o3);
        o3.setLayout(o3Layout);
        o3Layout.setHorizontalGroup(
            o3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(o3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(o3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        o3Layout.setVerticalGroup(
            o3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(o3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(o3);

        x4.setBackground(new java.awt.Color(204, 204, 204));
        x4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Najbolji X igrači u 4x4x4 igri:");

        topx4.setEditable(false);
        topx4.setColumns(20);
        topx4.setRows(5);
        jScrollPane2.setViewportView(topx4);

        javax.swing.GroupLayout x4Layout = new javax.swing.GroupLayout(x4);
        x4.setLayout(x4Layout);
        x4Layout.setHorizontalGroup(
            x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        x4Layout.setVerticalGroup(
            x4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(x4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(x4);

        o4.setBackground(new java.awt.Color(204, 255, 204));
        o4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Najbolji O igrači u 4x4x4 igri:");

        topo4.setEditable(false);
        topo4.setColumns(20);
        topo4.setRows(5);
        jScrollPane3.setViewportView(topo4);

        javax.swing.GroupLayout o4Layout = new javax.swing.GroupLayout(o4);
        o4.setLayout(o4Layout);
        o4Layout.setHorizontalGroup(
            o4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(o4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(o4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        o4Layout.setVerticalGroup(
            o4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(o4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(o4);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public static void crtaj() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ljestvicaPop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ljestvicaPop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ljestvicaPop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ljestvicaPop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ljestvicaPop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel o3;
    private javax.swing.JPanel o4;
    private javax.swing.JTextArea topo3;
    private javax.swing.JTextArea topo4;
    private javax.swing.JTextArea topx3;
    private javax.swing.JTextArea topx4;
    private javax.swing.JPanel x3;
    private javax.swing.JPanel x4;
    // End of variables declaration//GEN-END:variables
}
